[package]
name = "quarto_console"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quarto_game = { path = "../quarto_game" }
ansi_term = "0.12.1"
termion = "*"